config/routes.rb
Rails.application.routes.draw do

	root 'static_pages#index'
	devise_for :users
	# devise_for :users, controllers: { registrations: "registrations" }
	resources :books
	resources :authors
	post '/sort', to: "books#sort"
	get '/get_rq_json', to: "requests#get_rq_json"
	# post '/confirm', to: "carts#confirm"
	# get '/get_request_params', to: "carts#get_request_params"
	get "/my_cart/:id", to: "carts#my_cart"
	resources :carts do
		member do
			# get "confirm"
			post "confirm"
			get "accept"
			get "decline"
			get "detail"
		end
	end
	resources :requests 

end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :author
	#ManytoMany Book_Category
	has_many :bookcategories, dependent: :destroy
	has_many :categories, through: :bookcategories	#, source: :category
	accepts_nested_attributes_for :bookcategories, allow_destroy: true
 # 	#ManytoMany Book_Liked_User
 #   	has_many :likes, dependent: :destroy
 #   	has_many :liked_users, through: :likes, source: :user
	# #ManytoMany Book_Reviewed
	# has_many :reviews, dependent: :destroy
	# #Many to Many Poly Follow book, author
	# has_many :follows, as: :target, dependent: :destroy
	# has_many :followers, through: :follows, source: :user
	# #ManytoMany _Request details
	has_many :requests, dependent: :destroy
	has_many :users, through: :requests
	#Validate
	validates :name, presence: true, length: { maximum: 50 }
	validates :quantity, presence: true, length: { maximum: 1000 }

	has_attached_file :book_img, styles: { book_index: "250x350>", book_show: "325x475>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :book_img, content_type: /\Aimage\/.*\z/

 #  	def self.to_csv(option ={})
	# 	CSV.generate(option) do |csv|
	# 		csv << column_names
	# 		all.each do |book|
	# 			csv << book.attributes.values_at(*column_names)
	# 		end
	# 	end
	# end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

	before_action :find_book, only: [:show, :edit, :update, :destroy]
	before_action :find_user, only:[:show]
	helper_method :sort_direction


	def index
    	@categories = Category.all
		@authors = Author.all
		@q = Book.search(params[:q])
  		@search = @q.result(distinct: true)

  		
    	@pagy, @books = pagy_countless(@search.order("created_at DESC"), items: 9)
    	# @books = Book.all.order("created_at DESC").page(params[:page]).per_page(9)
    	@sort = ["Default","Name of book", "Name of author"]
    	respond_to do |format|
	      format.html
	      format.js
	      format.json {render json: @books}
	      # format.xls{send_data @full_books.to_csv(col_sep: "\t")}
    	end
    	# byebug
	end

	
	def show
		@q = Book.search(params[:q])
  		@search = @q.result(distinct: true)
		@categories = Category.all
		@authors = Author.all

		respond_to do |format|
	      format.html
	      format.js 
	      # format.xls{send_data @full_books.to_csv(col_sep: "\t")}
    	end
	end

	def edit; end

	def update
		if @book.update(book_params)
			flash[:success] = "Updating success"
			redirect_to book_path
		else
			flash[:danger] = "Updated failed"
			render 'edit'
		end
	end
	
	def new
		@book= Book.new
		@book.bookcategories.build
	end

	def create
		# byebug
		@book= Book.new(book_params)
		if @book.save
			flash[:success] = "Creating book success"
			redirect_to @book
		else
			flash[:danger] = "Creating book failed"
			render 'new'
		end
	end


	def destroy
		return unless @book.destroy
		redirect_to books_url
		flash[:success] = "Deleted book success"
	end

	def sort
			if params[:books]
				@books_request = convert params[:books].values
				respond_to do |format|
					format.html
					format.js
				end
			end
	end

	def convert arr
		newArr = []
		arr.each do |object|
	  		newMyObject = Book.new(object)
	  		newArr<<newMyObject
		end
		return newArr
	end
	# def followers
	# @book = Book.find(params[:book_id])
 #    @title = "Followers of book"
 #    @users = @book.followers
 #    render 'show_follow' 
 #    end

 #    def likes
	# @book = Book.find(params[:book_id])
 #    @title = "Likes of book"
 #    @users = @book.liked_users
    
 #    render 'show_follow' 
 #    end
    
	private

	def book_params
		params.require(:book).permit(:name, :quantity, :publisher, 
			:page, :author_id, :book_img,  
			bookcategories_attributes: [:book_id,:category_id,:_destroy])	
	end

	def find_book
		@book = Book.find(params[:id])
	end

	def find_user
		@user = current_user
	end

end

app/helpers/books_helper.rb
module BooksHelper
	def get_authors id
		Author.order(id)
	end
	def get_categories id
		Category.order(id)
	end

	def get_quantity book_id
		if Book.find(book_id).quantity > 0
			return Book.find(book_id).quantity  
		else
			return 0;
		end
	end
end

app/views/books/_banner.html.erb
 <section class="page-banner services-banner">
            <div class="container">
                <div class="banner-header">
                    <h2>Books & Media Listing</h2>
                    <span class="underline center"></span>
                    <p class="lead">Proin ac eros pellentesque dolor pharetra tempo.</p>
                </div>
                <div class="breadcrumb">
                    <ul>
                        <li><%= link_to "Home",root_path, method: :get%></li>
                        <li>Books & Media</li>
                    </ul>
                </div>
            </div>
</section>

app/views/books/_book.html.erb
<li>
    <div class="book-list-icon yellow-icon"></div>
    <figure>
        <a href="books/<%= book.id%>">
            <img src="../assets/books/<%= book.book_img_file_name %>" class="book_index" style="height: 450px; width: 355px">      
        </a>
        <figcaption>
            <header>
                <h4><%= link_to book.name, book,method: :get%></h4>
                <p><strong>Author:</strong><%= book.author.name %></p>
            </header>
            <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. Pellentesque dolor turpis, pulvinar varius.</p>
            <div class="actions">
                <ul>
                    <li>
                        <a href="#" target="_blank" data-toggle="blog-tags" data-placement="top" title="Add TO CART">
                            <i class="fa fa-shopping-cart"></i>
                        </a>
                    </li>
                    <li>
                        <a href="#" target="_blank" data-toggle="blog-tags" data-placement="top" title="Like">
                            <i class="fa fa-heart"></i>
                        </a>
                    </li>
                    <li>
                        <a href="#" target="_blank" data-toggle="blog-tags" data-placement="top" title="Print">
                            <i class="fa fa-print"></i>
                        </a>
                    </li>
                    <li>
                        <a href="#" target="_blank" data-toggle="blog-tags" data-placement="top" title="Share">
                            <i class="fa fa-share-alt"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </figcaption>
    </figure>                                                
</li>

app/views/books/_bookcategory_fields.html.erb
<div class="nested-fields field-w3-agile-grid leftf">
        <%= f.collection_select :category_id, Category.all, :id, :name,{:class => 'form-control'} %>
       	<%= link_to_remove_association "Remove category", f%>           
</div>

app/views/books/_search.html.erb
<!-- Start: Search Section -->
<section class="search-filters">
        <div class="container">
            <div class="filter-box">
                <h3>What are you looking for at the library?</h3>
                     <%= search_form_for @q do |f| %>
                        <div class="col-md-9 col-sm-6">
                            <div class="form-group">
                                <%= f.text_field :name_cont, class: "form-control",placeholder: "Search by name of book" %>
                            </div>
                        </div>
                        <!-- <div class="col-md-5 col-sm-6">
                            <div class="form-group">
                              
                            
                            </div>
                        </div> -->

                        <div class="col-md-3 col-sm-6">
                            <%= f.submit "Search", class: "form-control"%>
                        </div>
                    <% end %>  
            </div>
        </div>
</section>
<!-- End: Search Section -->

app/views/books/index.html.erb
<%= render "banner" %>
<div id="content" class="site-content">
        <div id="primary" class="content-area">
            <main id="main" class="site-main">
                <div class="books-media-list">
                    <div class="container">
                        <div class="row">
                               <%= render "search" %>
                        </div>
                    </div> 
                </div>
            </main>
            <div class="row">
                <div class="col-md-9 col-md-push-3">    
                    <div class="filter-options margin-list">
                        <div class="row">                                            
                            <div class="col-md-4 col-sm-4", style="margin-top: 11px;">
                                   <%= select_tag :sort, options_for_select(@sort), id:"list_sort", remote: true%>
                                  
                            </div>
                            <div class="col-md-4 col-sm-4">
                                <div class="filter-result" >
                                    <%= button_tag "Sort", id:"btn_sort"%>
                                    <span>Showing items 1 to 9 of <%= Book.count%> total</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
              <div>
                <div class="pagination" style="margin-left: 155px;"><%== pagy_bootstrap_nav(@pagy)%></div>
                <div style="float: right; margin-right: 150px;">
                  <a href="/books/new"><i class="fas fa-plus fa-4x " style="color: orange;" ></i></a>
                </div>
              </div>
                
                <div class="booksmedia-fullwidth">
                    <div class="row">
                        <div class="col-md-10 col-md-push-1">  
                            <ul id="book-index">              
                                <%=render @books%>
                            </ul>
                        </div>
                    </div>

                </div>
                <div class="pagination"  style="margin-left: 155px; margin-bottom: 40px;"><%==pagy_bootstrap_nav(@pagy)%></div>
            </div>
                        
        </div>
</div>

<script type="text/javascript">
    $('#btn_sort').click(function(){
        link = window.location.href + ".json"
        var selected = $('#list_sort').val()
        $.ajax({
          type: "GET",
          url: link,
          dataType: 'json',
          success: function(res){
            res.sort(function(a, b) {

              if (selected == "Name of book")
              {
                var nameA = a.name.toUpperCase(); // bỏ qua hoa thường
                var nameB = b.name.toUpperCase(); // bỏ qua hoa thường
              }
              else if (selected == "Name of Author")
              {
                var nameA = a.author.name.toUpperCase(); // bỏ qua hoa thường
                var nameB = b.author.name.toUpperCase(); // bỏ qua hoa thường
              }
              else if (selected == "Default")
              {
                var nameA = a.created_at.name; // bỏ qua hoa thường
                var nameB = b.created_at.name;
              }
              if (nameA < nameB) {
                return -1;
              }
              if (nameA > nameB) {
                return 1;
              }

              // name trùng nhau
              return 0;
            });
            console.log(res)
            $.ajax({
                type:"POST",
                url: "/sort",
                dataType: 'script',
                data: {books: res},
                success: function(response){
                },
                error:function(err){
                    console.log(err)
                }
            })
          },
          error:function(error){
            console.log(error)
          }
        });
    })
// alertify
//   .alert("This is an alert dialog.", function(){
//     alertify.message('OK');
//   });
</script>

app/views/books/new.html.erb
<%= render "banner" %>

<!-- Material form login -->
<div class="add-book">
	<h1>
		Form Add Book
	</h1>
	<div class="row">                                            
        <div class="col-md-8 col-sm-6", style="margin-top: 11px;">
               <%= form_for @book do |f| %>
	 	
		<%= f.text_field :name, placeholder: "Name", class: "form-control" %>
		<%= f.collection_select :author_id, Author.all, :id, :name, prompt: "Select author",class: "form-control"%>
		
		<%= f.collection_select :category_ids, Category.all, :id, :name, prompt: "Select category",class: "form-control cc"%>
		<% end %>
              
        </div>
        
	</div>	
</div>
      
    
<style type="text/css">
	.add-book{
		width: 50%;
		margin: auto;
		background-color: orange;
		margin-top: 100px;
	}
	.form-control{
		margin: auto;
		margin-top: 10px  !important;
		margin-bottom: 10px;
		margin-block-start: 10px !important;
		margin: 0 100px 0 100px !important;
	}
	.cc{
		width: 3%
	}
</style>

app/views/books/show.html.erb
<%= render "banner" %>
<div id="content" class="site-content">
        <div id="primary" class="content-area">
            <main id="main" class="site-main">
                <div class="books-media-list">
                    <div class="container">
                        <div class="row">
                             <%= render "search" %>
                        </div>
                    </div> 
                </div>
            </main>
            <div class="row">
                <div class="col-md-9 col-md-push-3">
                    <div class="booksmedia-detail-box">
                        <div class="single-book-box">                                                
                            <div class="post-thumbnail">
                                <div class="book-list-icon yellow-icon"></div>
                                <%= image_tag @book.book_img.url(:book_show), class: "book_show",style:"height: 450px; width: 320px;border: 7px solid #D3D3D3;"%>                                                    
                            </div>
                            <div class="post-detail" style="margin-right: 70px;">
                                <div class="books-social-sharing">
                                    <ul>
                                        <li><a href="#" target="_blank"><i class="fa fa-facebook"></i></a></li>
                                        <li><a href="#" target="_blank"><i class="fa fa-twitter"></i></a></li>
                                        <li><a href="#" target="_blank"><i class="fa fa-google-plus"></i></a></li>
                                        <li><a href="#" target="_blank"><i class="fa fa-rss"></i></a></li>
                                        <li><a href="#" target="_blank"><i class="fa fa-linkedin"></i></a></li>
                                    </ul>
                                </div>
                                <div class="optional-links">
                                    <ul>
                                        <li>
                                            <a href="#" target="_blank" data-toggle="blog-tags" data-placement="top" title="Add To Cart">
                                                <i class="fa fa-shopping-cart"></i>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#" target="_blank" data-toggle="blog-tags" data-placement="top" title="Like">
                                                <i class="fa fa-heart"></i>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#" target="_blank" data-toggle="blog-tags" data-placement="top" title="Mail"><i class="fa fa-envelope"></i>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#" target="_blank" data-toggle="blog-tags" data-placement="top" title="Search">
                                                <i class="fa fa-search"></i>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#" target="_blank" data-toggle="blog-tags" data-placement="top" title="Print">
                                                <i class="fa fa-print"></i>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                                <header class="entry-header">
                                    <h2 class="entry-title"><%= @book.name %></h2>
                                    <ul>
                                        <li><strong>Author:</strong> <%= link_to @book.author.name, @book.author,method: :get, class: "book-author"%></li>
                                        <li><strong>ISBN:</strong> 9781581573268</li>
                                        <li><strong>Edition:</strong> First edition</li>
                                        <li><strong>Publisher:</strong> <%= @book.publisher%></li>
                                        <li><strong>Quantity:</strong> <%= get_quantity(@book.id)%></li>
                                    </ul>
                                </header>
                                <div class="entry-content post-buttons">
                                    <%= link_to requests_path(book_id: @book.id),
                                    {
                                        class: "add-to-cart btn btn-dark-gray",
                                        method: :post, 
                                        remote: true
                                    } do%>
                                        <i class="fas fa-shopping-cart"></i> Add to Cart
                                    <% end %>
                                </div>
                            </div>
                        </div>
                        <p style="margin-right: 50px;"><strong>Summary:</strong> <%=@book.content%></p>
                        <ul class="detail-page-listing">
                            <li><strong>Length:</strong> <%= @book.page%> Pages</li>
                            <li><strong>Format:</strong> DVD</li>
                            <li><strong>Language Note:</strong> Icelandic dialogue; English subtitles.</li>
                            <li><strong>Genre :</strong> Feature films, Fiction films, Drama</li>
                             <li><strong>Topics:</strong> Friendship, Bullies, Pranks, School</li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-3 col-md-pull-9">
                    <aside id="secondary" class="sidebar widget-area" data-accordion-group="">
                        <div class="widget widget_related_search open" data-accordion="" style="margin-left: 20px">
                            <h4 class="widget-title" data-control="">Related Searches</h4>
                            <div data-content="" style="transition: max-height 300ms ease 0s; max-height: 228px; overflow: hidden;">
                                <div data-accordion="" class="">
                                    <h5 class="widget-sub-title" data-control="">Categories</h5>
                                    <div class="widget_categories" data-content="" style="max-height: 0px; overflow: hidden; transition: max-height 300ms ease 0s;">
                                        <ul>
                                            <% @categories.each do |c| %>
                                                <li><a href="#"><%= c.name %><span>(<%=c.books.count%>)</span></a></li>
                                            <% end %>
                                        </ul>
                                    </div>
                                </div>
                                <div data-accordion="" class="">
                                    <h5 class="widget-sub-title" data-control="">Authors</h5>
                                    <div class="widget_categories" data-content="" style="max-height: 0px; overflow: hidden; transition: max-height 300ms ease 0s;">
                                        <ul>
                                            <% 5.times do |i|%>
                                                <% a = @authors[i] %>
                                                <li>
                                                    <%= link_to a.name+" ("+a.books.count.to_s+")", a, method: :get %>
                                                </li>
                                            <% end %>
                                        </ul>
                                    </div>
                                    <div class="clearfix"></div>
                                </div>

                            </div>
                            <div class="clearfix"></div>
                        </div>
                    </aside>
                </div>
            </div>
        </div>
</div>
<style type="text/css">
    a.book-author{
       color: #ff7236;     
    }
    a.book-author:hover
       {
        color: gray;
    }
</style>
<script type="text/javascript">
$('.add-to-cart').click(function(){
    var user = "<%= current_user.nil?%>"
    if (user == "true")
    {
         alertify
         .alert("Please login!").setHeader('<em>Thong bao</em>');
    }
    else
    {   
        var check_quantity ="<%= get_quantity(@book.id) %>"
        var check_dup_book = "<%= check_item_cart(@book.id) %>"
        if (check_quantity == "0")
        {
            alertify
            .alert("Out of stock").setHeader('<em>Thong bao</em>');
        }
        else
        {   
            if (check_dup_book == "true")
            {
                alertify
                .alert("Duplicate item in cart!").setHeader('<em>Thong bao</em>');
            }
            else
            {   
                //ajax {
                    //type:GET
                // }
                alertify
                .alert("Added to cart").setHeader('<em>Thong bao</em>');
                if($('.carts-append li').text() == "Emptying")
                {    
                    $('.carts-append').html("<%= j render partial: "requests/item", object: @book, as: :book %>")
                    $('.carts-append').append("<%= j render partial: "layouts/view_cart_btn" %>")
                }
                else
                {   
                    $('.carts-append').prepend("<%= j render partial: "requests/item", object: @book, as: :book %>")
                }
            }
            
        }
    }
    
   
  
})
  
</script>

app/views/books/sort.js.erb
$('#book-index').html("<%= j  render partial: 'book', collection: @books_request %>")