config/routes.rb
Rails.application.routes.draw do

	root 'static_pages#index'
	devise_for :users
	# devise_for :users, controllers: { registrations: "registrations" }
	resources :books
	resources :authors
	post '/sort', to: "books#sort"
	get '/get_rq_json', to: "requests#get_rq_json"
	# post '/confirm', to: "carts#confirm"
	# get '/get_request_params', to: "carts#get_request_params"
	get "/my_cart/:id", to: "carts#my_cart"
	resources :carts do
		member do
			# get "confirm"
			post "confirm"
			get "accept"
			get "decline"
			get "detail"
		end
	end
	resources :requests 

end

app/models/cart.rb
class Cart < ApplicationRecord
	
	belongs_to :user

	# attr_accessor :current_user

	has_many :requests, dependent: :destroy
		
	has_many :books, through: :request, source: :book

	scope :carts_admin, -> {where "verify not like '3'"} 

	# scope :carts_user, -> {where user_id: current_user.id, verify: !3}

	

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	# before_action :set_user
	before_action :find_user
	# before_action :find_book, only: [:new, :create, :show]
	before_action :find_cart, only: [:decline,:undo_quantity,:destroy,:accept]
	# before_action :find_request, only: [:destroy]
	# before_action :find_user_cart, only: [:update_request_params,:accept,:decline,:confirm, :update_quantity,:show]
	before_action :find_detail_cart, only: [:detail]
	before_action :cart_and_request, only:[:show,:confirm,:update_request_params]

	def index
		@carts = Cart.carts_admin.order("created_at DESC")
	end

	def show
		@requests = @list_requests.order("created_at DESC")
		# respond_to do |format|
		# 	    format.html
		#     	format.js
		#     	format.json{render json: @requests}
		# end
	end

	def detail
		@requests_detail = Request.where(cart_id: @cart_detail.id)
	end

	def my_cart
		return @carts = Cart.where("verify not like '3' and user_id"+"= "+ @user.id.to_s).order("created_at DESC") if user_signed_in?
	end

	# def get_request_params dateto, number
	# 	dateto = params["dateto"] # get dateto tu tren view ve 
	# 	number = params["number"] # get number tu tren view ve
	# 	update_request_params(dateto,number)

	# end

	def update_request_params dateto,number
		session[:dateto] = dateto
		session[:number] = number
		book_arr = []
		check = 0
		@list_requests.each_with_index do |r,dem|
			if dateto  && number
				book_arr[dem] = Book.find(r.book_id)
				if book_arr[dem].quantity >= session[:number][dem].to_i && session[:dateto][dem].to_date > Time.zone.now.to_date
					r.update_attributes(number: session[:number][dem].to_i,datefrom: Time.zone.now.to_date, dateto: session[:dateto][dem].to_date)
					book_arr[dem].quantity = book_arr[dem].quantity - r.number
				else
					check = 3
					break
				end
			end
		end
		# if verify == 3 return = 0 update quantity
		if check == 0
			book_arr.each_with_index do |b,index|
				book = Book.find_by(id:b.id)
				book.update_attributes(quantity: b.quantity)
			end
			@cart.update_attributes(verify: 0)
		else
			return nil
		end
	end

	def confirm
		dateto = params["dateto"] # get dateto tu tren view ve 
		number = params["number"] # get number tu tren view ve
		update_request_params dateto, number
		@user.carts.create if @cart.verify != 0 
		respond_to do |f|
			f.js 
		end
	end

	def accept 
	    @cart.verify = 1
	    if @cart.save
	    	# RequestMailer.reply_email(@request).deliver
	    	# flash[:success] = "Accept request"
	    	redirect_to carts_url
	    else
	    	# render action: "index"
		end
  	end

  	

  	def decline
	    	undo_quantity
	    	redirect_to carts_url if @cart.save
	    	# RequestMailer.reply_email(@request).deliver
	    	# flash[:danger] = "Decline request"
  	end	

  	def update_request
  		
  	end

  	def destroy
  		undo_quantity 
  		redirect_to "/my_cart/:id(.:format)" if @cart.destroy
  	end
	
	private

		def find_book
			@book = Book.find(params[:book_id])
		end

		def find_user
			@user = current_user
		end

		def find_cart

			@cart = Cart.find(params[:id])
		end

		def find_user_cart
			@cart = Cart.find(params[:id])
		end

		def find_detail_cart
			@cart_detail = Cart.find(params[:id])
		end

		def find_request
			@requests = Request.where(cart_id: @cart.id)
		end

		def cart_and_request
			@cart = Cart.find(params["id"])
			@list_requests = Request.where("cart_id = "+@cart.id.to_s)
		end

		def request_params
			params.require(:request).permit(:number,:dateto)
		end

		def undo_quantity
		 	@requests = Request.where("cart_id = "+ @cart.id.to_s)
			@requests.each do |r|
				@book = Book.find(r.book_id)
				@book.update_attributes(quantity: @book.quantity + r.number)
			end
			@cart.verify = 2
		end 
end

app/helpers/carts_helper.rb
module CartsHelper
	# def requests 
 #    @cart = Cart.where(user_id: current_user.id).last if current_user
 #    if  @cart.nil? || @cart.verify != 3
 #      return nil 
 #    else
 #      @requests = Request.where(cart_id: @cart.id)
 #    end
 #  end
end

app/views/carts/_banner.html.erb
<!-- Start: Page Banner -->
<section class="page-banner services-banner">
    <div class="container">
        <div class="banner-header">
            <h2>Cart Page</h2>
            <span class="underline center"></span>
            <p class="lead">Proin ac eros pellentesque dolor pharetra tempo.</p>
        </div>
        <div class="breadcrumb">
            <ul>
                <li><a href="index.html">Home</a></li>
                <li>Dashboard</li>
            </ul>
        </div>
    </div>
</section>

app/views/carts/_cart.html.erb
<tr>
	<% u = User.find(c.user_id) %>
	<td><%= u.name %></td>
	<td><%= u.email%></td>
	<td><%= c.requests[0].datefrom %></td>
	<% if check_status(c) == "Pending" %>
		<td>
			<%= link_to "", accept_cart_path(c) ,class: "fas fa-check fa-2x",style: "color: green" %>
			<%= link_to "", decline_cart_path(c) ,class: "fa fa-times fa-2x",style: "color: red; padding-left: 30px;"%>
		</td>
	<% else %>
		<% if  check_status(c) == "Accept" %>
			<td style="color: green"><%= check_status(c) %></td>
		<% elsif check_status(c) == "Decline" %>
			<td style="color: red"><%= check_status(c) %></td>
		<% end %>
	<% end %>
	<td>
		<%= link_to "", detail_cart_path(c), class: "fas fa-info fa-2x",style: "color: #035777; padding-left: 17px" %>
	</td>
</tr>

app/views/carts/_detail.html.erb
<tr>
	<% book = Book.find(r.book_id) %>
	<td><%= link_to (image_tag ("books/"+book.book_img_file_name),style:"height: 120px; width: 70px"),book,method: :get%></td>
	<td><%= book.name %></td>
	<td><%= r.number %></td>
	<td><%= r.datefrom%>
	<td><%= r.dateto%></td>		
</tr>

app/views/carts/_my_cart.html.erb
<tr>
	<% u = User.find(c.user_id) %>
	<td><%= u.name %></td>
	<td><%= u.email%></td>
	<td><%= c.requests[0].datefrom %></td>
	<% if check_status(c) == "Accept" %>
		<td style="color: green"><%= check_status(c) %></td>	
	<% elsif check_status(c) == "Decline" %>
		<td style="color: red;"><%= check_status(c) %></td>
	<% elsif check_status(c) == "Pending" %>
		<td style="color: orange;"><%= check_status(c) %></td>
	<% end %>
	<td>
		<% if check_status(c) == "Pending"  %>
			<%= link_to "", cart_path(c.id), method: :delete,class: "fa fa-trash fa-2x",style: "color: #77032F" %> <span class="fa-2x">/</span>
			<%= link_to "", detail_cart_path(c), class: "fas fa-info fa-2x",style: "color: #035777" %>
		<% else %>
			<%= link_to "", detail_cart_path(c), class: "fas fa-info fa-2x",style: "color: #035777; padding-left: 17px" %>
		<% end %>
		
	</td>	
</tr>

app/views/carts/_notice.html.erb
<% flash.each do |message_type, message| %>
        <h4><%= content_tag(:div, message, class: "alert alert-#{message_type}") %></h4>
<% end %>

app/views/carts/_request.html.erb
<%= form_for r do |f| %>
	<tr>
		<% book = Book.find(r.book_id) %>
		<td><%= link_to (image_tag ("books/"+book.book_img_file_name),style:"height: 120px; width: 70px"),book,method: :get%></td>
		<td><%= f.label :number,value: book.quantity, readonly: true%></td>
		<td><%= f.number_field :number, in: 1..book.quantity, value:1%></td>
		<td><%= f.date_field :datefrom, min: Date.today, value: Date.today, readonly: true%>
		<td><%= f.date_field :dateto, min: Date.today+1, value: Date.today+1%></td>		
		<td>
			<%= link_to r, class: "remove remove-item", method: :delete, data:{confirm: "You sure?"} do %>
            	<i class="fa fa-trash-o"></i>
       		<% end %>
    	</td>		
	</tr>
<% end %>

app/views/carts/confirm.js.erb
var check = "<%= @cart.verify %>"
if(check == 3)
{
	window.location.href = "/carts/"+"<%= @cart.id%>"
	// console.log(check)
}
else
{
	window.location.href = "/my_cart/"+"<%= @user.id%>"
}

app/views/carts/detail.html.erb
<%= render "banner" %>

<% if @requests_detail  %>
  <div class="table-users">
    <div class="header">Carts</div>
      <table cellspacing="0">
        <tr>
           <th width="20%">Book</th>
           <th width="20%">Namebook</th>
           <th width="10%">Get</th>
           <th width="25%">DayFrom</th>
           <th width="25%">DayTo</th>
        </tr>
        <% @requests_detail.each do |r| %>
          <%= render partial: "carts/detail", object: r, as: :r %>
        <% end %>
      </table>
  </div>
<% else %>
  <h1 style="text-align: center; margin-top: 100px;">
    Your cart is emptying <i class="far fa-frown"></i>
  </h1>
<% end %>

app/views/carts/index.html.erb
<%= render "banner" %>
      <!-- # 3: carting, 0:pending, 1: accept, 2: decline -->
<% if @carts && @carts.last && !@carts.last.requests.blank?%>
	<div class="table-users" style="margin-top: 70px;">
	   <div class="header">History of Trading</div>
	   
	   <table cellspacing="0">
	      <tr>
	         <th>User</th>
	         <th>Email</th>
	         <th>Date</th>
	         <th>Accept/Decline</th>
	         <th>Option</th>
	      </tr>

	      <% @carts.each do |c| %>
	      	<%= render partial: "carts/cart", object: c, as: :c %>
	      <% end %>
	      
	   </table>
	</div>
<% else %>
	<h1 style="text-align: center; margin-top: 100px;">
		Users's Cart is emptying <i class="far fa-frown"></i>
	</h1>
	<%= link_to books_url  do %>
  		<h3 style="text-align: center; ">
		 	<i class= "fas fa-arrow-right"></i>Go to Book & Media
		</h3>
	<% end %>
<% end %>

app/views/carts/my_cart.html.erb
<%= render "banner" %>
      <!-- # 3: carting, 0:pending, 1: accept, 2: decline -->
<% if user_signed_in? && @carts  && @carts.last && !@carts.last.requests.blank?%>
	<div class="table-users" style="margin-top: 70px;">
	   <div class="header">History of Trading</div>
	   <table cellspacing="0">
	      <tr>
	         <th>User</th>
	         <th>Email</th>
	         <th>Date</th>
	         <th>Status</th>
	         <th>Option</th>
	      </tr>

	      <% @carts.each do |c| %>
	      	<%= render partial: "carts/my_cart", object: c, as: :c %>
	      <% end %>
	      
	   </table>
	</div>
<% else %>
	<h1 style="text-align: center; margin-top: 100px;">
		Your history's cart is emptying <i class="far fa-frown"></i>
	</h1>
	<%= link_to books_url  do %>
  		<h3 style="text-align: center; ">
		 	<i class= "fas fa-arrow-right"></i>Go to Book & Media
		</h3>
	<% end %>
<% end %>

app/views/carts/show.html.erb
<%= render "banner" %>
<% if @cart.verify == 3 %>
  <div class="table-users">
    <div class="header">Carts</div>
      <table cellspacing="0">
        <tr>
           <th>Book</th>
           <th>Available</th>
           <th>Get</th>
           <th style="width: 70px;">DayFrom</th>
           <th style="width: 70px;">DayTo</th>
           <th style="width: 10px;">Option</th>
        </tr>
        <% @requests.each do |r|  %>
          <%= render partial: "carts/request", object: r, as: :r %>
        <% end %>
      </table>
  </div>
    <div style="float:right; margin-right: 19%">
      <%= link_to "Borrow", confirm_cart_path(@cart.id), id: "borrow"%>
    </div>
<% else %>
  <h1 style="text-align: center; margin-top: 100px;">
    Your cart is emptying <i class="far fa-frown"></i>
  </h1>
<% end %>



<script type="text/javascript">
 
 link = window.location.href
  
  // $('#request_number').change(function(e){
  //   if($(this).val() > 100)
  //   {
  //     e.preventDefault();
  //   }
  // })

  var dateto = Array.from(document.querySelectorAll("#request_dateto"));
  var quantity = Array.from(document.querySelectorAll("#request_number"))
  var arr1 = dateto.map(d=>d.value)
  var  arr2 = quantity.map(d=>d.value)
  console.log(quantity)
  $(document).on('click keyup','#request_number, #request_dateto', function(){
    quantity = Array.from(document.querySelectorAll("#request_number"))
    dateto = Array.from(document.querySelectorAll("#request_dateto"))
    arr2 = quantity.map(d=>d.value)
    arr1 = dateto.map(d=>d.value)
    // console.log(arr1)
  })
  // $(document).on('click','#request_dateto', function(){
  //   var d = Array.from(document.querySelectorAll("#request_dateto"))
  //   dateto = d;
  //    var arr1 = dateto.map(d=>d.value)

  // })
 // var dateto = Array.from(document.querySelectorAll("#request_dateto"));
 // var quantity = Array.from(document.querySelectorAll("#request_quantity_get"));

   // console.log(arr2)
   $('#borrow').click(function(e){
      // console.log(arr2)
      e.preventDefault();
       var i = 0;
       $.ajax({
          method: "POST",
          url: "/carts/"+"<%=@cart.id%>"+"/confirm",
          data: {"dateto": arr1, "number": arr2},
          dataType: "script",
          success: function(res)
          {
            // i = i +1;
            // window.location.href = "/books"
            console.log(res)
            // console.log(i.toString())
          },
          error: function(err)
          {
            console.log(err)
          }
        })    
   })
    
 //  update_params() 
 //  for (var i = 0; i < dateto.length; i++) {
 //    dateto[i].addEventListener("change", function() {
 //      update_params()
 //    });
 //  }
 //  for (var i = 0; i < quantity.length; i++) {
 //    quantity[i].addEventListener("change", function() {
 //      update_params()
 //    });
 //  }
</script>