config/routes.rb
Rails.application.routes.draw do

	root 'static_pages#index'
	devise_for :users
	# devise_for :users, controllers: { registrations: "registrations" }
	resources :books
	resources :authors
	post '/sort', to: "books#sort"
	get '/get_rq_json', to: "requests#get_rq_json"
	# post '/confirm', to: "carts#confirm"
	# get '/get_request_params', to: "carts#get_request_params"
	get "/my_cart/:id", to: "carts#my_cart"
	resources :carts do
		member do
			# get "confirm"
			post "confirm"
			get "accept"
			get "decline"
			get "detail"
		end
	end
	resources :requests 

end

app/views/layouts/_alert.html.erb
<p class="alert alert-success"><%= notice %></p>
<p class="alert alert-danger"><%= alert %></p>

app/views/layouts/_cart.html.erb
<div class="header-cart dropdown">
    <a data-toggle="dropdown" class="dropdown-toggle" href="#" id="item-count">
        <i class="fa fa-shopping-cart"></i>
        <% if requests %>
            <small><%=requests.count%></small>
        <% else %>
            <small>0</small>
        <% end %>
        
    </a>
    <div class="dropdown-menu cart-dropdown">
        <% if user_signed_in? %> 
            <ul class="carts-append">
                <% if !requests.nil?  && requests.count !=0  %>
                    <% requests.each do |r| %>
                       <%= render partial: "/layouts/item", object: r, as: :r %>
                    <% end %>
                    <%= render "layouts/view_cart_btn" %>
                <% else %>
                     <li style="margin-top: 17px; text-align: center;">Emptying</li>
                <% end%>
            </ul>
        <% else %>
            <li style="margin-top: 17px;"><%= link_to "Please login",new_user_session_path,method: :get %> </li>
        <% end %>
    </div>
</div>

app/views/layouts/_footer.html.erb
 <!-- Start: Footer -->
          <!-- Start: Social Network -->
        <section class="social-network section-padding">
            <div class="container">
                <div class="center-content">
                    <h2 class="section-title">Follow Us</h2>
                    <span class="underline center"></span>
                    <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                </div>
                <ul>
                    <li>
                        <a class="facebook" href="http://www.fb.com/mrahn123" target="_blank">
                            <span>
                                <i class="fa fa-facebook-f"></i>
                            </span>
                        </a>
                    </li>
                    <li>
                        <a class="twitter" href="#" target="_blank">
                            <span>
                                <i class="fa fa-twitter"></i>
                            </span>
                        </a>
                    </li>
                    <li>
                        <a class="google" href="#" target="_blank">
                            <span>
                                <i class="fa fa-google-plus"></i>
                            </span>
                        </a>
                    </li>
                    <li>
                        <a class="rss" href="#" target="_blank">
                            <span>
                                <i class="fa fa-rss"></i>
                            </span>
                        </a>
                    </li>
                    <li>
                        <a class="linkedin" href="#" target="_blank">
                            <span>
                                <i class="fa fa-linkedin"></i>
                            </span>
                        </a>
                    </li>
                    <li>
                        <a class="youtube" href="#" target="_blank">
                            <span>
                                <i class="fa fa-youtube"></i>
                            </span>
                        </a>
                    </li>
                </ul>
            </div>
        </section>
        <!-- End: Social Network -->
        <footer class="site-footer">
            <div class="container">
                <div id="footer-widgets">
                    <div class="row">
                        <div class="col-md-4 col-sm-6 widget-container">
                            <div id="text-2" class="widget widget_text">
                                <h3 class="footer-widget-title">About Libraria</h3>
                                <span class="underline left"></span>
                                <div class="textwidget">
                                    It is a long established fact that a reader will be distracted by the readable content of a page when looking.
                                </div>
                                <address>
                                    <div class="info">
                                        <i class="fa fa-location-arrow"></i>
                                        <span>21 King Street, Melbourne, Victoria 3000 Australia</span>
                                    </div>
                                    <div class="info">
                                        <i class="fa fa-envelope"></i>
                                        <span><a href="mailto:support@libraria.com">support@libraria.com</a></span>
                                    </div>
                                    <div class="info">
                                        <i class="fa fa-phone"></i>
                                        <span><a href="tel:012-345-6789">+ 012-345-6789</a></span>
                                    </div>
                                </address>
                            </div>
                        </div>
                        <div class="col-md-2 col-sm-6 widget-container">
                            <div id="nav_menu-2" class="widget widget_nav_menu">
                                <h3 class="footer-widget-title">Quick Links</h3>
                                <span class="underline left"></span>
                                <div class="menu-quick-links-container">
                                    <ul id="menu-quick-links" class="menu">
                                        <li><a href="#">Library News</a></li>
                                        <li><a href="#">History</a></li>
                                        <li><a href="#">Meet Our Staff</a></li>
                                        <li><a href="#">Board of Trustees</a></li>
                                        <li><a href="#">Budget</a></li>
                                        <li><a href="#">Annual Report</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="clearfix hidden-lg hidden-md hidden-xs tablet-margin-bottom"></div>
                        <div class="col-md-2 col-sm-6 widget-container">
                            <div id="text-4" class="widget widget_text">
                                <h3 class="footer-widget-title">Timing</h3>
                                <span class="underline left"></span>
                                <div class="timming-text-widget">
                                    <time datetime="2017-02-13">Mon - Thu: 9 am - 9 pm</time>
                                    <time datetime="2017-02-13">Fri: 9 am - 6 pm</time>
                                    <time datetime="2017-02-13">Sat: 9 am - 5 pm</time>
                                    <time datetime="2017-02-13">Sun: 1 pm - 6 pm</time>
                                    <ul>
                                        <li><a href="#">Closings</a></li>
                                        <li><a href="#">Branches</a></li>
                                    </ul>
                                </div>
                            </div>			
                        </div>
                        <div class="col-md-4 col-sm-6 widget-container">
                            <div class="widget twitter-widget">
                                <h3 class="footer-widget-title">Latest Tweets</h3>
                                <span class="underline left"></span>
                                <div id="twitter-feed">
                                    <ul>
                                        <li>
                                            <p><a href="#">@TemplateLibraria</a> Sed ut perspiciatis unde omnis iste natus error sit voluptatem. <a href="#">template-libraria.com</a></p>
                                        </li>
                                        <li>
                                            <p><a href="#">@TemplateLibraria</a> Sed ut perspiciatis unde omnis iste natus error sit voluptatem. <a href="#">template-libraria.com</a></p>
                                        </li>
                                    </ul>
                                </div>
                            </div>			
                        </div>
                    </div>
                </div>                
            </div>
        </footer>
        <!-- End: Footer -->

app/views/layouts/_header.html.erb
<!-- Start: Header Section -->
        <header id="header-v1" class="navbar-wrapper">
            <div class="container">
                <div class="row">
                    <nav class="navbar navbar-default">
                        <div class="row">
                            <div class="col-md-3">
                                <div class="navbar-header">
                                    <div class="navbar-brand">
                                        <h1>
                                            <a>
                                                <img src="/assets/libraria-logo-v1.png" alt="LIBRARIA" />
                                            </a>
                                        </h1>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-9">
                                <!-- Header Topbar -->
                                <div class="header-topbar hidden-sm hidden-xs">
                                    <div class="row">
                                        <div class="col-sm-6">
                                            <div class="topbar-info">
                                                <a href="tel:+61-3-8376-6284"><i class="fa fa-phone"></i>+0774455559</a>
                                                <span>/</span>
                                                <a href="mailto:support@libraria.com"><i class="fa fa-envelope"></i>support@libraria.com</a>
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="topbar-links">
                                                <% if user_signed_in? %>
                                                    <a><i class="fa fa-lock"></i><%= link_to current_user.name  %> | <%= link_to "Sign out", destroy_user_session_path, method: :delete  %> </a> 
                                                <% else %>
                                                       <a><i class="fa fa-lock"></i><%= link_to "Login /", new_user_session_path,method: :get %><%= link_to " Register", new_user_registration_path, method: :get%></a>
                                                <% end %>
                                                <span>|</span>
                                                <%= render "/layouts/cart" %>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="navbar-collapse hidden-sm hidden-xs">
                                    <ul class="nav navbar-nav">
                                        <li class="dropdown active">
                                            <a><%= link_to "Home", root_path, method: :get %></a>
                                        </li>
                                        <li class="dropdown">
                                            <a data-toggle="dropdown" class="dropdown-toggle disabled" >
                                                <%= link_to "Books & Media", books_path, method: :get %>
                                            </a>
                                            <ul class="dropdown-menu">
                                                <li><%= link_to "Books", books_path, method: :get %></li>
                                                <li><%= link_to "Authors", authors_path, method: :get %></li></li>
                                                <li><a href="#">Categories</a></li>
                                            </ul>
                                        </li>
                                        <li><a href="#">Services</a></li>
                                        <li><a href="#">Contact</a></li>
                                        <li class="dropdown">
                                            <% if user_signed_in? %>
                                                <a data-toggle="dropdown" class="dropdown-toggle disabled" href="#"><%= link_to "Cart", cart_path(cart_id) %></a>
                                                <ul class="dropdown-menu">
                                                    <li><%= link_to "Cart", cart_path(cart_id) %></li>
                                                    <li> <%= link_to "History of Cart", "/my_cart/"+ current_user.id.to_s, method: :get %></li>
                                                </ul>
                                            <% else %>
                                                <a data-toggle="dropdown" class="dropdown-toggle disabled" href="#"><%= link_to "Cart", new_user_session_path %></a>
                                                <ul class="dropdown-menu">
                                                    <li><%= link_to "Cart", new_user_session_path %></li>
                                                    <li> <%= link_to "History of Cart", new_user_session_path, method: :get %></li>
                                                </ul>
                                            <% end %>
                                            
                                        </li>
                                        <% if user_signed_in? && current_user.role == 1 %>
                                            <li class="dropdown">
                                                <a data-toggle="dropdown" class="dropdown-toggle disabled" href="#">Manage</a>
                                                <ul class="dropdown-menu">
                                                     <li><%= link_to "Manage of cart", carts_path, method: :get %></li>
                                                     <li><%= link_to "Manage of user"%></li>
                                                </ul>
                                            </li> 
                                        <% end %>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="mobile-menu hidden-lg hidden-md">
                            <a href="#mobile-menu"><i class="fa fa-navicon"></i></a>
                            <div id="mobile-menu">
                                <ul>
                                    <li class="mobile-title">
                                        <h4>Navigation</h4>
                                        <a href="#" class="close"></a>
                                    </li>
                                    <li>
                                        <a>Home <%=link_to root_path, method: :get%></a>
                                        <ul>
                                            <li><a href="index-2.html">Home V1</a></li>
                                            <li><a href="home-v2.html">Home V2</a></li>
                                            <li><a href="home-v3.html">Home V3</a></li>
                                        </ul>
                                    </li>
                                    <li>
                                        <a href="books-media-list-view.html">Books &amp; Media</a>
                                        <ul>
                                            <li><a href="books-media-list-view.html">Books &amp; Media List View</a></li>
                                            <li><a href="books-media-gird-view-v1.html">Books &amp; Media Grid View V1</a></li>
                                            <li><a href="books-media-gird-view-v2.html">Books &amp; Media Grid View V2</a></li>
                                            <li><a href="books-media-detail-v1.html">Books &amp; Media Detail V1</a></li>
                                            <li><a href="books-media-detail-v2.html">Books &amp; Media Detail V2</a></li>
                                        </ul>
                                    </li>
                                    <li>
                                        <a href="news-events-list-view.html">News &amp; Events</a>
                                        <ul>
                                            <li><a href="news-events-list-view.html">News &amp; Events List View</a></li>
                                            <li><a href="news-events-detail.html">News &amp; Events Detail</a></li>
                                        </ul>
                                    </li>
                                    <li>
                                        <a href="#">Pages</a>
                                        <ul>
                                            <li><a href="cart.html">Cart</a></li>
                                            <li><a href="checkout.html">Checkout</a></li>
                                            <li><a href="signin.html">Signin/Register</a></li>
                                            <li><a href="404.html">404/Error</a></li>
                                        </ul>
                                    </li>
                                    <li>
                                        <a href="blog.html">Blog</a>
                                        <ul>
                                            <li><a href="blog.html">Blog Grid View</a></li>
                                            <li><a href="blog-detail.html">Blog Detail</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="services.html">Services</a></li>
                                    <li><a href="contact.html">Contact</a></li>
                                </ul>
                            </div>
                        </div>
                    </nav>
                </div>
            </div>
        </header>
        <!-- End: Header Section -->

app/views/layouts/_item.html.erb
 <li class="clearfix">
    <div id="cart-item-delete">
        <% book = Book.find(r.book_id)%>
        <%= link_to (image_tag ("books/"+book.book_img_file_name), style:"height: 70px; width: 45px; margin-top: 30px"),book,method: :get%>
        <div class="item-info">
            <div class="name">
                <%= link_to book.name, book %>
            </div>
            <div class="author"><strong>Author:</strong> <%= book.author.name%></div>
        </div>
        <%= link_to r, class: "remove remove-item", method: :delete, data:{confirm: "You sure?"} do %>
            <i class="fa fa-trash-o"></i>
        <% end %>
    </div>
</li>

app/views/layouts/_view_cart_btn.html.erb
<% if user_signed_in?%>
		<div class="cart-buttons">
	    	<%= link_to "View Cart", cart_path(cart_id) ,class: "btn btn-dark-gray" %>
		</div>
<% end %>
	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Your Library</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>

    
    <meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1">
  </head>
  <%= render 'layouts/header' %>
  <body>
    <%= yield %>
    
  </body>
  <%= render 'layouts/footer' %>
</html>